// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compteservice.proto

package grpcgrpc.grpc5.stubs;

public interface GetAllComptesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetAllComptesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Compte comptes = 1;</code>
   */
  java.util.List<grpcgrpc.grpc5.stubs.Compte> 
      getComptesList();
  /**
   * <code>repeated .Compte comptes = 1;</code>
   */
  grpcgrpc.grpc5.stubs.Compte getComptes(int index);
  /**
   * <code>repeated .Compte comptes = 1;</code>
   */
  int getComptesCount();
  /**
   * <code>repeated .Compte comptes = 1;</code>
   */
  java.util.List<? extends grpcgrpc.grpc5.stubs.CompteOrBuilder> 
      getComptesOrBuilderList();
  /**
   * <code>repeated .Compte comptes = 1;</code>
   */
  grpcgrpc.grpc5.stubs.CompteOrBuilder getComptesOrBuilder(
      int index);
}
