// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compteservice.proto

package grpcgrpc.grpc5.stubs;

public interface GetTotalSoldeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetTotalSoldeRequest)
    com.google.protobuf.MessageOrBuilder {
}
