// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compteservice.proto

package grpcgrpc.grpc5.stubs;

public interface SaveCompteRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SaveCompteRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.CompteRequest compte = 1;</code>
   * @return Whether the compte field is set.
   */
  boolean hasCompte();
  /**
   * <code>.CompteRequest compte = 1;</code>
   * @return The compte.
   */
  grpcgrpc.grpc5.stubs.CompteRequest getCompte();
  /**
   * <code>.CompteRequest compte = 1;</code>
   */
  grpcgrpc.grpc5.stubs.CompteRequestOrBuilder getCompteOrBuilder();
}
